### PR TITLE
chore: update tag to 0.21.1

### PR DESCRIPTION
**Pull request by darren-rose**
### Motivation

upgrade to version 0.21.1 @bonomat @thomaseizinger

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
LGTM.

We need to create a `0.21.1` branch after this is merged.

**Comment by darren-rose** [comment]
@thomaseizinger could someone with write access merge this?

**Comment by darren-rose** [comment]
> LGTM.
> 
> We need to create a `0.21.1` branch after this is merged.

Could you merge?

**Comment by thomaseizinger** [comment]
It seems that building these images now requires a pro plan on docker hub. Meaning this update won't get built automatically. We may want to transition to GitHub container registry.

cc @bonomat

**Pull request merged**
